# Generated by Django 5.2.3 on 2025-06-12 15:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='None', max_length=120)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='uploads/audios/transcript_generator/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='uploads/audios/transcript_generator/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
